name: macOS 15 ARM Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/sub_buildPixi.yml
    with:
      artifactBasename: macOS-15-arm-${{ github.run_id }}
      runnerOS: '["macos-15"]'
